### ISSUE TITLE
running very slow on Windows 10

### ISSUE THREAD

**Issue by JesseB0rn** [nutki/spike-tools#1]
Runs very slow on Windows 10.

**Comment by nutki** [comment]
Can you describe which exact command you are using? Is it naive Python on Python in WSL? I never used this on Windows, but I can try and see what is happening.

**Comment by nutki** [comment]
@JesseB0rn Can you try again? I made some changes for spikejsonrpc tool to work faster for me under WSL (now it matches my Linux results which is still slower than the cp.py).

**Comment by ws1088** [comment]
what is the requirements/instructions to run on Windows 10? I would like to try it out.

**Comment by nutki** [comment]
@ws1088 This is a guide from MS how to use Python on Windows: https://docs.microsoft.com/en-us/windows/python/beginners
I have WSL Ubuntu installed on my Windows machine so this is what I used.
I've used USB connection to the hub which showed up in the device manager as 'COM7' so in WSL this mapped to `/dev/ttyS7`. I guess when using the native Windows Python, the device name (`-t` parameter value) should be just `COM7` in such case.

**Comment by nutki** [comment]
@ws1088 @JesseB0rn 
I got it to work with Python 3.8 from the Microsoft Store with the following (in PowerShell):
```
pip install --upgrade pip
pip install -r requirements.txt
python spikejsonrpc.py -t COM7 fwinfo
```
Copy speed is similar to WSL and native Linux.
